using System.Collections;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>Short-lived, local-only warnings generated by networked crystal events.</summary>
[DisallowMultipleComponent]
public sealed class FactionCrystalAlertHud : MonoBehaviour
{
    private TextMeshProUGUI label;
    private CanvasGroup canvasGroup;
    private Coroutine hideRoutine;

    public static FactionCrystalAlertHud GetOrCreate()
    {
        FactionCrystalAlertHud existing = FindFirstObjectByType<FactionCrystalAlertHud>();
        if (existing != null)
        {
            return existing;
        }

        GameObject root = new("Faction Crystal Alert", typeof(Canvas), typeof(CanvasScaler), typeof(GraphicRaycaster), typeof(CanvasGroup));
        Canvas canvas = root.GetComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 70;
        CanvasScaler scaler = root.GetComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920f, 1080f);

        FactionCrystalAlertHud hud = root.AddComponent<FactionCrystalAlertHud>();
        hud.canvasGroup = root.GetComponent<CanvasGroup>();
        GameObject labelObject = new("Alert", typeof(RectTransform));
        labelObject.transform.SetParent(root.transform, false);
        hud.label = labelObject.AddComponent<TextMeshProUGUI>();
        hud.label.font = TMP_Settings.defaultFontAsset;
        hud.label.fontSize = 31f;
        hud.label.alignment = TextAlignmentOptions.Center;
        hud.label.outlineColor = new Color(0.04f, 0.05f, 0.1f, 1f);
        hud.label.outlineWidth = 0.22f;
        RectTransform rect = hud.label.rectTransform;
        rect.anchorMin = new Vector2(0.5f, 1f);
        rect.anchorMax = new Vector2(0.5f, 1f);
        rect.pivot = new Vector2(0.5f, 1f);
        rect.anchoredPosition = new Vector2(0f, -112f);
        rect.sizeDelta = new Vector2(1080f, 90f);
        root.SetActive(false);
        return hud;
    }

    public void Show(int factionIndex, int health, int maximumHealth, bool destroyed, bool protectedNow)
    {
        FusionDuckPlayer localPlayer = FindLocalPlayer();
        bool isOwnCrystal = localPlayer != null && localPlayer.FactionIndex == factionIndex;
        string factionName = FactionTeam.GetName(factionIndex);
        label.color = destroyed ? new Color(1f, 0.48f, 0.4f) : FactionTeam.GetColor(factionIndex);
        label.text = destroyed
            ? (isOwnCrystal ? "警報！己方水晶已毀壞" : factionName + "方水晶已毀壞")
            : protectedNow
                ? (isOwnCrystal ? "己方水晶已獲得護盾並回復生命" : factionName + "方水晶啟動護盾")
                : (isOwnCrystal ? "警報！己方水晶遭受攻擊" : factionName + "方水晶受損")
                  + "　" + health + " / " + maximumHealth;

        gameObject.SetActive(true);
        canvasGroup.alpha = 1f;
        if (hideRoutine != null)
        {
            StopCoroutine(hideRoutine);
        }
        hideRoutine = StartCoroutine(HideAfterDelay());
    }

    private IEnumerator HideAfterDelay()
    {
        yield return new WaitForSeconds(3.4f);
        float elapsed = 0f;
        while (elapsed < 0.35f)
        {
            elapsed += Time.deltaTime;
            canvasGroup.alpha = 1f - elapsed / 0.35f;
            yield return null;
        }
        gameObject.SetActive(false);
        hideRoutine = null;
    }

    private static FusionDuckPlayer FindLocalPlayer()
    {
        FusionDuckPlayer[] players = FindObjectsByType<FusionDuckPlayer>(
            FindObjectsInactive.Exclude,
            FindObjectsSortMode.None);
        for (int index = 0; index < players.Length; index++)
        {
            if (players[index] != null && players[index].HasStateAuthority)
            {
                return players[index];
            }
        }
        return null;
    }
}
